data_generator_cfg:
  processing_queue: [anjie_seg, kersen_locate, kersen_seg]
  set_all_labels_ok: False
  seed: 42
  delimiter: '||'
  tasks:
    - task_name: anjie_seg
      base_dir: DATASETS/cropped
      img_json_dirs:
        # - ['20230320-0619/20230320-46', '20230320-0619_jsonv2/20230320-46']
        # - ['20230320-0619/20230328-81', '20230320-0619_jsonv2/20230328-81']
        # - ['20230320-0619/20230329-81', '20230320-0619_jsonv2/20230329-81']
        # - ['20230625-0629', '20230625-0629_jsonv1']
        # - ['20230703/46石墨_修改v2', null]
        # - ['20230703/0701-81-石墨超区域图_新标注', '20230703/0701-81-石墨超区域图_新标注_修改v2_json']
        # - ['20230705', null]
        - ['20230728', null]
        - ['20230803', null]
        - ['20230805', null]
      train_ratio: 0.8
      generate_cfgs:
        - tags: ['light', '_1.', '_ 10.']
          save_dir: DATASETS/datalist_temp/mingchang
          datalist_names:
            train: trainlist_20230728-0805.txt
            test: testlist_20230728-0805.txt
            unknown: null
        - tags: ['dusky', '_2.', '_ 11.']
          save_dir: DATASETS/datalist_temp/anchang
          datalist_names:
            train: trainlist_20230728-0805.txt
            test: testlist_20230728-0805.txt
            unknown: null

    - task_name: kersen_locate
      base_dir: Kersen_DATASETS/origin
      img_json_dirs:
        - ['20230720', 'bianyuan_20230720-0729_json/20230720']
        - ['20230724', 'bianyuan_20230720-0729_json/20230724']
        - ['20230725', 'bianyuan_20230720-0729_json/20230725']
        - ['20230729', 'bianyuan_20230720-0729_json/20230729']
      train_ratio: 0.8
      generate_cfgs:
        - tags: ['.jpg']
          save_dir: Kersen_DATASETS/datalist_temp/locate
          datalist_names:
            train: trainlist_20230720-0729.txt
            test: testlist_20230720-0729.txt
            unknown: null

    - task_name: kersen_seg
      base_dir: Kersen_DATASETS/cropped
      img_json_dirs:
        - ['20230729', null]
        - ['20230802', null]
        - ['20230804', null]
      train_ratio: 0.8
      generate_cfgs:
        - tags: ['light', '_1.', '_ 10.']
          save_dir: Kersen_DATASETS/datalist_temp/mingchang
          datalist_names:
            train: trainlist_20230729-0804.txt
            test: testlist_20230729-0804.txt
            unknown: null
        - tags: ['dusky', '_2.', '_ 11.']
          save_dir: Kersen_DATASETS/datalist_temp/anchang
          datalist_names:
            train: trainlist_20230729-0804.txt
            test: testlist_20230729-0804.txt
            unknown: null

image_cropper_cfg:
  # base_dir: DATASETS/origin
  # img_json_dirs:
  #   - ['20230728', null]
  #   - ['20230803', null]
  #   - ['20230805', null]
  # save_dir: DATASETS/cropped_temp
  # grayscale: True
  # save_as_jpg: False
  # is_draw: False
  # only_json: False
  # enable_time_printing: False
  # roi_mappings:
  #   # - tags: ['20230320-46']
  #   #   product_type: '46'
  #   #   roi_list: null
  #   # - tags: ['20230328-81']
  #   #   product_type: '81'
  #   #   roi_list: null
  #   # - tags: ['20230329-81']
  #   #   product_type: '81'
  #   #   roi_list: null
  #   # - tags: ['_else_']
  #   #   product_type: '81'
  #   #   roi_list: null
  #   - tags: ['_46_']
  #     product_type: '46'
  #     roi_list: null
  #   - tags: ['_81_']
  #     product_type: '81'
  #     roi_list: null

  base_dir: Kersen_DATASETS/origin
  img_json_dirs:
    - ['20230729', null]
    - ['20230802', null]
    - ['20230804', null]
  save_dir: Kersen_DATASETS/cropped_temp
  grayscale: True
  save_as_jpg: False
  is_draw: False
  only_json: True
  enable_time_printing: False
  roi_mappings:
    - tags: ['_46_']
      product_type: '46'
      roi_list: null
    - tags: ['_81_']
      product_type: '81'
      roi_list: null


  locate_pipeline_cfg:
    type: LocatePipeline
    loc_module_cfg:
      type: SegModuleBase
      label_map: ['bianyuan']
      preprocess_cfg: 
        - type: Resize
          output_size: [512, 768]
        - type: Normalize
          mean: [0.5]
          std: [1.0]
          scale: [1.0]
      engine_cfg:
        type: Onnx2TensorRTEngine
        model_path: CodeDeploy/pipeline_data/models/locate_0806_v1.onnx
        md5: a2d2caf4fb5778eb2580c4ab7571828b
      output_cfg:
        output_contours: true
        output_mask: true
        output_contours_area: true
        output_score_map: false
        output_rects: true
      postprocess_cfg: 
        - type: FilterMask
          area_thresholds: [80000000]

  locate_cropped_cfg:
    - product_type: '46'
      cropped_params:
        - contour_sort_mode: null
          contour_index: 0
          anchor_position: center
          anchor_offset: [0, 0]
          output_size: [14000, 20000]
    - product_type: '81'
      cropped_params:
        - contour_sort_mode: null
          contour_index: 0
          anchor_position: center
          anchor_offset: [0, 0]
          output_size: [11900, 17000]
